--- 
Measurement_units: feet
LargeLockers: 
    length: 15
    width: 15
    height: 15
    totalAmount: 1000
MediumLockers: 
    length: 10
    width: 10
    height: 10
    totalAmount: 1000	
SmallLockers: 
    length: 5
    width: 5
    height: 5
    totalAmount: 1000
